version: '3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
    networks:
      - demo-network
    ports:
      - 27017:27017

networks:
  demo-network: