version: '3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
    networks:
      - demo-network
    ports:
      - 27017:27017

  server:
    build:
      context: ./backend
    networks:
      - demo-network
    ports:
      - 3000:3000
    environment:
      NODE_ENV: docker
    depends_on:
      - mongo

networks:
  demo-network: