version: '3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
    networks:
      - demo-network
    ports:
      - 27017:27017

  server:
    build:
      context: ./backend
    networks:
      - demo-network
    ports:
      - 3000:3000
    environment:
      NODE_ENV: docker
    depends_on:
      - mongo
  
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    volumes:
      - ./swagger:/opt/swagger
    environment:
      SWAGGER_JSON: /opt/swagger/openapi.yml
      SERVER_AJAX_DOMAIN: http://localhost:3000
    depends_on:
      - mongo

networks:
  demo-network:
