import { model, Schema, PaginateModel} from "mongoose";
import idValidator from "mongoose-id-validator";
import paginate from 'mongoose-paginate-v2';

/**
 * Newspaper spec definition
 */
export interface NewspaperInterface {
  _id: number;
  title: string;
  image: string;
  link: string;
  abstract: string;
  publisher: number;
  languages: Array<string>;
  creation_date?: Date;
}

const NewspaperSchema = new Schema<NewspaperInterface>(
  {
    //Note that id refers to mongo _id
    _id: { type: Number, alias: "id" },
    title: { type: String, required: true },
    image: { type: String, required: true },
    link: { type: String, required: true, validate: {
      validator: (v:string) => {
        //Validate URL against regex
        const urlRegex = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-/]))?/;
        return urlRegex.test(v);
      },
      message: "Link must be a valid URL"
    }},
    abstract: { type: String, required: true },
    publisher: {
      //publisher is a reference of a publisher entity
      type: Number,
      ref: "Publisher",
      required: true
    },
    languages: {
      type: [String],
      validate: {
        validator: (v: Array<string>) => v.length > 0,
        message: `Languages cannot be empty`,
      },
    },
  },
  {
    //creation_date is autogenerated when document is inserted
    timestamps: {
      createdAt: "creation_date",
      updatedAt: false
    },
  }
);

NewspaperSchema.set('toJSON', {
  transform: function (doc, ret, options) {
      //Restore id from _Id and remove __v mongoose param
      ret.id = ret._id;
      delete ret._id;
      delete ret.__v;
  }
});

//Validate publisher against publisher database
NewspaperSchema.plugin(idValidator, {message: "Publisher not found"});
//Add pagination
NewspaperSchema.plugin(paginate);

export const Newspaper = model<NewspaperInterface, PaginateModel<NewspaperInterface>>(
  "Newspaper",
  NewspaperSchema
);
